export const FETCH_STARTED = "FETCH_STARTED";
export const FETCH_COMPLETED = "FETCH_COMPLETED";

export const USER_DETAILS = "USER_DETAILS";
export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED";
export const CLEAR_USER_DETAILS_STATUS = "CLEAR_USER_DETAILS_STATUS";

//Register new User
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

//Get All Products
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILED = "GET_ALL_PRODUCTS_FAILED";

//Product Details
//Get All Products
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_LOADING = "GET_PRODUCT_DETAILS_LOADING";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILED = "GET_PRODUCT_DETAILS_FAILED";

//Add Item To Cart
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const ADD_ITEM_TO_CART_LOADING = "ADD_ITEM_TO_CART_LOADING";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAILED = "ADD_ITEM_TO_CART_FAILED";

//Cart Itms
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";

//Login Status

export const LOGGED_IN = "LOGGED_IN";

// Add to Wishlist
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const ADD_TO_WISHLIST_LOADING = "ADD_TO_WISHLIST_LOADING";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILED = "ADD_TO_WISHLIST_FAILED";
export const CLEAR_ADD_TO_WISHLIST_STATUS = "CLEAR_ADD_TO_WISHLIST_STATUS";

// Remove from Wishlist
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const REMOVE_FROM_WISHLIST_LOADING = "REMOVE_FROM_WISHLIST_LOADING";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_FAILED = "REMOVE_FROM_WISHLIST_FAILED";
export const CLEAR_REMOVE_FROM_WISHLIST_STATUS =
  "CLEAR_REMOVE_FROM_WISHLIST_STATUS";

//wishlist Items
export const WISHLIST_ITEMS = "WISHLIST_ITEMS";
